### ISSUE TITLE
Citations broken?

### ISSUE THREAD

**Issue by ethman** [source-separation/tutorial#20]
Somehow citation links and rendering is broken :(

**Comment by justinsalamon** [comment]
Yup, perhaps something changed in the API? Have you had a chance to investigate this?

**Comment by wwymak** [comment]
the bibtex reference is missing from the config.yml file-- if you add
```yaml
bibtex_bibfiles:
    - references.bib
```

to _config.yml that'll fix the citations

**Comment by ethman** [comment]
Awesome! Thanks! That fixed it. I'm not sure if that line got deleted somehow or if the API changed like Justin suggested, but thanks so much for finding the fix @wwymak!

**Comment by justinsalamon** [comment]
thanks @wwymak @ethman !
