### ISSUE TITLE
Issue on page /basics/evaluation.html

### ISSUE THREAD

**Issue by MessyPaste** [source-separation/tutorial#30]
The definition of SNR is different from the paper(Performance Measurement in Blind Audio Source Separation). I think you make a mistake here.

**Comment by ethman** [comment]
Hi! Thanks for checking out the tutorial. Sorry for the confusion, the SNR equation is actually from the second paper referenced in that section [(see eq. (1) here)](http://www.jonathanleroux.org/pdf/LeRoux2019ICASSP05sdr.pdf), which is a more standard definition of SNR than the definition in the Emmanuel Vincent paper. I thought the Le Roux definition more clearly conveyed what SNR captures.

**Comment by MessyPaste** [comment]
Thank you!
