### ISSUE TITLE
Issue on page /basics/evaluation.html

### ISSUE THREAD

**Issue by MordehayM** [source-separation/tutorial#33]
I think the terms you have wrote about SNR and SDR there are the same, the denominator of both is the same..

So what is the differnce between them?

**Comment by ethman** [comment]
Yeah, you're 100% correct. In fact, depending on how you use them, there's not too much of a difference between SDR and SNR in many cases. But the devil is in the details! This tutorial is not designed to give a deep dive into every derivation; notice that that there is no definition for the error terms $e_{interf}$, $e_{noise}$, and $e_{artif} on the page you mention. Rather, we're trying to provide an overview of the field and give readers an intuition for common terms that they'll encounter.

If you want to learn exact details about these measures, how they're used, critiques etc, check out the following papers:
- [Performance Measurement in Blind Audio Source Separation](http://recherche.ircam.fr/equipes/analyse-synthese/vincent/vincent_IEEE04.pdf) (Vincent et. al., 2006)
- [First Stereo Audio Source Separation Evaluation Campaign: Data, Algorithms and Results](https://hal.inria.fr/inria-00544199/file/vincent_ICA07.pdf) (Vincent et. al., 2007)
- [Subjective and objective quality assessment of audio source separation](https://hal.inria.fr/file/index/docid/485729/filename/RR-7297.pdf) (Vincent et. al., 2011)
- [The 2018 Signal Separation Evaluation Campaign](https://arxiv.org/pdf/1804.06267.pdf) (Stöter et. al., 2018)
- [SDR–half-baked or well done?](http://www.jonathanleroux.org/pdf/LeRoux2019ICASSP05sdr.pdf) (Le Roux et. al, 2019)

**Comment by MordehayM** [comment]
Ok, realy good overview of the field.
Thanks.
